name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 17
    # Unfortunately, npm still has a bug where 'prepare' doesn't automatically install
    # the 'devDependencies': https://github.com/npm/cli/issues/1865
    # Since nighthouse has a dev-dependency on @types/node, we need to install it manually.
    - name: Install @types/node as a workaround
      run: npm install -g @types/node
    - name: Install dependencies
      run: npm install
    - name: Build packages
      run: npm run build

